services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: traccio
      POSTGRES_PASSWORD: traccio
      POSTGRES_DB: traccio
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    name: traccio.db
    driver: local
